- name: Configure /etc/ovs-ifup
  copy:
    dest: "/etc/ovs-ifup"
    content: |
        #!/bin/sh
        switch='ovs0'
        /sbin/ifconfig $1 0.0.0.0 up
        ovs-vsctl add-port ${switch} $1

- name: Configure /etc/ovs-ifup
  copy:
    dest: "/etc/ovs-ifup"
    content: |
        #!/bin/sh
        switch='ovs0'
        /sbin/ifconfig $1 0.0.0.0 down
        ovs-vsctl del-port ${switch} $1

 
- name: "Copying over /etc/sysconfig/network-scripts/ifcfg-{{ ifcfg_interface }}"
  template:
    src: templates/ifcfg-item.j2
    dest:  "/etc/sysconfig/network-scripts/ifcfg-{{ ifcfg_interface }}"
    owner: "root"
    group: "root"
    mode: 0666

 
- name: Copying over ifcfg-ovs0 file
  template:
    src: templates/ifcfg-ovs0.j2
    dest:  "/etc/sysconfig/network-scripts/ifcfg-ovs0"
    owner: "root"
    group: "root"
    mode: 0666

- name: enable openvswitch.service
  systemd:
    name: openvswitch.service
    state: started
    enabled: yes

- name: restart network.service
  systemd:
    name: network.service
    state: restarted
    enabled: yes

- name: running command ovs-vsctl show
  command: ovs-vsctl show
  register: ovsvsctloutput

- name: Result of ocs-vsctl
  debug:
    var: ovsvsctloutput.stdout