---
- name: MSIO | Networking | OpenVSwitch | Install Packages
  include: openvswitch_install_fedora.yml
  when: ansible_facts['distribution'] == "Fedora"
- name: Networking | OpenVSwitch | Build Bridges (external,internal,sparta)
  openvswitch_bridge:
    bridge: external
    state: present
- openvswitch_bridge:
    bridge: internal
    state: present
- openvswitch_bridge:
    bridge: sparta
    state: present
