---

#- name: Grub | Grubby | Add kernel parameters
#  command: grubby --args="{ item}" --update-kernel=ALL
#  with_items: "{{ args_grub_fedora }}"
- name: Grub | Grubby | Add kernel parameters
  command: grubby --args="{{ item }}" --update-kernel=ALL
  with_items: "{{ args_grub_fedora }}"
