#!/usr/bin/ansible-playbook --inventory=inventory
- name: ' Koffer | Artifact Rake Utility' 
  hosts: local
  vars:
    module: 'devkit'
    ansible_name_module: ' Sparta | Devkit'
    sparta_path: '{{ local_home }}/Sparta/Git'
  vars_files:
    - 'vars/git.yml'

- import_playbook: tree.yml         # Create base deploy directory tree
- import_playbook: git.yml          # Pull git repos
