#!/usr/local/bin/ansible-playbook --inventory=inventory
- name: ' Sparta | Devkit'
  hosts: local
  vars:
    module: 'devkit'
    ansible_name_module: ' Sparta | Devkit'
    sparta_path: '{{ local_home }}/Sparta/Git'
  vars_files:
    - 'vars/git.yml'

- import_playbook: ./code/commit.yml          # Commit active devel branch to git
