#!/usr/bin/ansible-playbook --inventory=inventory
- name: ' Sparta | Devkit | git.yml'
  hosts: local
  vars_files:
    - 'vars/global.yml'
    - 'vars/git.yml'
  vars:
    module: "git"
    ansible_name_module: "{{ ansible_name }} | {{ module }}"
  tasks:

    - name: '{{ ansible_name_module }} | git:clone | Clone Sparta Git Repositories' 
      git:
        clone: yes
        version: "{{ item.branch }}"
        repo: "{{ item.repo }}"
        dest: "{{ item.dest }}"
        update: true
        force: yes
        key_file: "{{ item.key_file }}"
      with_items:
        - "{{ basicrepos }}"
        - "{{ terraformrepos }}"
    
    - name: '{{ ansible_name_module }} | shell:terraform.init | Initilize terraform modules'
      shell: 
        cmd: terraform init
        chdir: "{{ item.dest }}"
      with_items:
        - "{{ terraformrepos }}"
