#!/usr/bin/ansible-playbook --inventory=inventory
# Rough play to allow for automated CodeSparta feature branch coding & trunk development
- name: ' Sparta | Devkit | commit.yml'
  hosts: local
  vars_files:
    - '../vars/global.yml'
    - '../vars/git.yml'
  vars:
    module: "git"
    ansible_name_module: "{{ ansible_name }} | {{ module }}"
    git_remote: origin
  tasks:

    - name: '{{ ansible_name_module }} | shell:git.checkout | Git Checkout {{ git_checkout }}'
      shell:
        cmd: "git stage -A"
        chdir: "{{ item.dest }}"
      with_items:
        - "{{ basicrepos }}"
      ignore_errors: True

    - name: '{{ ansible_name_module }} | shell:git.checkout | Git Checkout {{ git_checkout }}'
      shell:
        cmd: "git commit -m {{ git_msg }}"
        chdir: "{{ item.dest }}"
      with_items:
        - "{{ basicrepos }}"
      ignore_errors: True

    - name: '{{ ansible_name_module }} | shell:git.branch | Git Branch {{ git_checkout }}'
      shell:
        cmd: "git push {{ git_remote }} {{ git_branch }}"
        chdir: "{{ item.dest }}"
      with_items:
        - "{{ basicrepos }}"
      ignore_errors: True
