#!/usr/bin/ansible-playbook --inventory=inventory
# Rough play to allow for automated CodeSparta feature branch coding & trunk development
- name: ' Sparta | Devkit | commit.yml'
  hosts: local
  vars_files:
    - '../vars/global.yml'
    - '../vars/git.yml'
  vars:
    module: "git"
    ansible_name_module: "{{ ansible_name }} | {{ module }}"
    message: "Release {{ tag }}"
  tasks:

    - name: '{{ ansible_name_module }} | shell:git.tag | Git Tag Project'
      shell:
        cmd: 'git tag -a {{ tag }} -m "{{ message }}"'
        chdir: "{{ item.dest }}"
      with_items:
        - "{{ basicrepos }}"
      ignore_errors: True

    - name: '{{ ansible_name_module }} | shell:git.push.origin | Git Push {{ branch }}'
      shell:
        cmd: "git push {{ remote }} --tags"
        chdir: "{{ item.dest }}"
      with_items:
        - "{{ basicrepos }}"
