---
# Install Libvirt on Fedora
- name: Install Libvirt on Fedora
  become: yes
  package:
    name: "{{ packages_libvirt_fedora }}"
    state: present
- modprobe:
    name: kvm_intel
    params: 'nested=1'
- modprobe:
    name: vfio-pci
