---
packages_ovs_fedora:
  - openvswitch
  - network-scripts-openvswitch

packages_ova_rhel8:
  - openvswitch

packages_ova_rhel7:
  - wget
  - openssl-devel
  - python-sphinx
  - gcc
  - make
  - python-devel
  - openssl-devel
  - kernel-devel
  - graphviz
  - kernel-debug-devel
  - autoconf
  - automake
  - rpm-build
  - redhat-rpm-config
  - libtool
  - python-twisted-core
  - python-zope-interface
  - PyQt4
  - desktop-file-utils
  - libcap-ng-devel
  - groff
  - checkpolicy
  - selinux-policy-devel
  - unbound
  - unbound-devel
  - gcc-c++
