# htpasswd -c -B -b /tmp/users.htpasswd ocadmin admin
# oc create secret generic htpasswd-secret --from-file=htpasswd=/tmp/users.htpasswd -n openshift-config
# oc apply -f https://raw.githubusercontent.com/CodeSparta/devkit/master/config/htpasswd.yml
# oc adm policy add-cluster-role-to-user cluster-admin ocadmin
# oc delete secrets kubeadmin -n kube-system
#############################################################################
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: htpasswd_provider 
    mappingMethod: claim 
    type: HTPasswd
    htpasswd:
      fileData:
        name: htpasswd-secret
