---
galaxy_info:
  author: "ContainerCraft.io"
  description: CCIO MiniStack - Setup Networking Topologies
  company: "ContainerCraft.io"
  license: GPLv3
  min_ansible_version: 2.5
  platforms:
    - name: Fedora
      versions:
        - all
        - 31
    - name: EL
      versions:
        - 7
        - 8
  galaxy_tags:
    - rhel
    - centos
    - fedora
  dependencies: []
