---
# Install Base Packages on Fedora
- name: Install Base Packages on Fedora OS
  become: yes
  package:
    name: "{{ packages_wireguard_fedora }}"
    state: present
- name: Enable Wireguard Kernel Module
  become: yes
  modprobe:
    name: wireguard
    state: present
