#!/usr/local/bin/ansible-playbook --inventory=inventory
- name: ' Sparta | Devkit | Libvirt Hypervisor'
  hosts: libvirt
  vars:
    module: 'devkit'
    ansible_name_module: ' Sparta | Devkit'
  vars_files:
    - vars/global.yml

- import_playbook: network-setup.yml     # Implement host network architecture
- import_playbook: hypervisor-setup.yml     # Build host hypervisor layer
