---
# Configure snapd
- name: add users to the lxd secondary group
  user:
    name: "{{ item }}"
    append: yes
    groups: lxd
  with_items: root
# with_items: "{{ lxd_users }}"
  become: yes
- name: Reset ssh connection to allow user changes to affect current user
  meta: reset_connection
- name: /snap/bin/lxd init --auto
  command: /snap/bin/lxd init --auto
  args:
    creates: /var/snap/lxd/common/lxd/storage-pools/default
  become: yes
