---
# Install lxd from snap
- name: install lxd snap
  become: yes
  snap:
    name: lxd
    channel: latest/edge
- name: restart the snapd service
  systemd:
    name: snapd.service
    enabled: yes
    state: restarted
  become: yes
- name: Snapd Ready Workaround - part1
  command: snap list 
  ignore_errors: yes
- name: Snapd Ready Workaround - part2
  command: sleep 30
  ignore_errors: yes
- name: install lxd snap
  become: yes
  snap:
    name:
      - snapd
