- name: devkit-bastion | Terraform for MacOS
  block:
    - name: devkit-bastion | Download binary for MacOSX
      get_url:
        url: https://releases.hashicorp.com/terraform/0.14.4/terraform_0.14.4_darwin_amd64.zip
        dest: "{{ software_install_directory }}"

    - name: devkit-bastion | Install Terraform
      unarchive:
        src: "{{ software_install_directory }}/terraform_0.14.4_darwin_amd64.zip
        dest: "/usr/local/bin/"
  when: ansible_distribution == "MacOSX"

- name: devkit-bastion | Terraform for Linux (RedHat and CentOS)
  block:
    - name: devkit-bastion | Download Terraform Binary for RHEL/CentOS
      get_url:
        url: https://releases.hashicorp.com/terraform/0.14.4/terraform_0.14.4_linux_amd64.zip 
        dest: "{{ software_install_directory }}"

    - name: devkit-bastion | Install Terraform
      unarchive:
        src: "{{ software_install_directory }}/terraform_0.14.4_darwin_amd64.zip"
        dest: "/usr/local/bin/"
  when: ansible_distribution == "RedHat" or ansible_distribution == "CentOS"
