---
- name: checking configure_ovs_packages value
  debug:
    var: configure_ovs_packages
    verbosity: 2

- name: Check that the openvswitch rpm exists
  stat:
    path: /home/ovs/rpmbuild/RPMS/x86_64/openvswitch-2.12.0-1.el7.x86_64.rpm
  become: yes
  register: ovs_rpm

- name: Install Required packages for OVS build on RedHat Enterprise Linux 7.x
  yum:
    name: "{{ item }}"
    state: present
  loop: "{{ packages_ova_rhel7 }}"
  become: yes
  when: not ovs_rpm.stat.exists

- name: Run a build-ovs-on-rhel7.sh
  script: files/build-ovs-on-rhel7.sh
  when: not ovs_rpm.stat.exists

- name: Check that the openvswitch rpm exists
  stat:
    path: /home/ovs/rpmbuild/RPMS/x86_64/openvswitch-2.12.0-1.el7.x86_64.rpm
  become: yes
  register: ovs_rpm

- name: install openvswitch rpm locally
  yum:
    name: /home/ovs/rpmbuild/RPMS/x86_64/openvswitch-2.12.0-1.el7.x86_64.rpm
    state: present
  become: yes
  when: ovs_rpm.stat.exists
