---
- name: Enable openstack-15-for-rhel-8-x86_64-rpms RHSM repository
  rhsm_repository:
    name: openstack-15-for-rhel-8-x86_64-rpms

- name: Enable fast-datapath-for-rhel-8-x86_64-rpms RHSM repository
  rhsm_repository:
    name: fast-datapath-for-rhel-8-x86_64-rpms

# Install Base Packages on RHEL 8 
- name: Install Base Packages on RHEL 8 
  become: yes
  package:
    name: "{{ packages_ova_rhel8 }}"
    state: present
