---
# tasks file for kvm
- include: install_RedHat7.x.yml
  when: ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_version']|int == 7
- include: install_RedHat8.x.yml
  when: ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_version']|int == 8
- include: install_Fedora.yml
  when: ansible_facts['distribution'] == "Fedora" and ansible_facts['distribution_version']|int <= 31
- include: install_Fedora.yml
  when: ansible_facts['distribution'] == "Fedora" and ansible_facts['distribution_version']|int <= 32
